changed

diff --git a/.github/workflows/php.yml b/.github/workflows/php.yml
--- a/.github/workflows/php.yml
+++ b/.github/workflows/php.yml
@@ -54,40 +54,33 @@ jobs:
       - name: Rebase main onto dev
         if: ${{ success() }}
         run: |
-        # Проверка наличия локальных изменений перед добавлением в stash
           if [ -n "$(git status --porcelain)" ]; then
-          git stash push -m "Temporary save"
+            git stash push -m "Temporary save"
           fi
 
-          # Проверка существования ветки main
           if git show-ref --verify --quiet refs/heads/main; then
-          git checkout main
+            git checkout main
           else
-          echo "Main branch does not exist locally. Fetching from remote."
-          git fetch origin main:main
-          git checkout main
+            echo "Main branch does not exist locally. Fetching from remote."
+            git fetch origin main:main
+            git checkout main
           fi
 
-          # Ребейс main на текущую ветку (предполагается, что dev — текущая ветка)
           git rebase dev --strategy-option theirs || {
-          echo "Rebase failed. Aborting rebase.";
-          git rebase --abort;
-          exit 1;
-        }
+            echo "Rebase failed. Aborting rebase.";
+            git rebase --abort;
+            exit 1;
+          }
 
-          # Закоммитить изменения, если ребейс добавил что-то новое
           if [ -n "$(git status --porcelain)" ]; then
-          git add .
-          git commit -m "Rebase main onto dev with resolved conflicts"
+              git add .
+              git commit -m "Rebase main onto dev with resolved conflicts"
           fi
 
-          # Запушить изменения
           git push origin main --force-with-lease
 
-          # Вернуться на предыдущую ветку
           git checkout dev
 
-          # Вернуть сохранённый коммит из stash, если он был
           if git stash list | grep -q "Temporary save"; then
-          git stash pop
+            git stash pop
           fi
